application: analyzecal
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /.*
  script: main.py

libraries:
- name: jinja2
  version: 2.6
